version: 1
validation: sovereign
default_denom: uplt

accounts:
  - name: bootstrap
    coins:
      - 100000000uplt
client:
  openapi:
    path: docs/static/openapi.json

validators:
  - name: bootstrap
    bonded: 100000000uplt
